# Annualized volatility predictions

Author: Pete King

In our analysis, we measured performance of three different types of models to predict realized volatility for an asset: a Ridge regressor, a Gradient Boosting Regressor (GBR), and a Long Short-Term Memory (LSTM) deep-learning model.  For each model type, we tested performance using three different sets of input features: a 'limited' set relying primarily on historical (realized) volatility, a 'full' set including 87 engineered features, and a 'PCA' set of 13 extracted features (along with historical return and historical volatility).

We conducted a preliminary analysis to asses the best-performing combination of model type and feature set according to a set of criteria, testing the performance of those models using a validation set.  From these preliminary tests, we selected the LSTM models, since those using the 'limited' or 'PCA' set of features displayed superior performance according to our evaluation criteria.

Then, for the chosen model type, we conducted 30 trials.  In each trial, we trained the models on the training set data and then used them to provide a set of weekly predictions (forecast) for **realized** volatility.  We collected predictions for the training set, validation set, and test set, but we only consider performance on the test set in this notebook.

The final component of our "Portfolio Generator" requires a prediction of **annualized** volatility for each ETF.  Here we convert the model's predictions of realized volatility to annualized volatility for each ETF, and compute two values:

 - An average value for annualized volatility over the entire test set (over 30 trials, with 61 weekly predictions in each trial)

 - A median value of annualized volatility for the latest available prediction in the test set (again over 30 trials, but considering only the final prediction for Week 61)

The first figure represents our best estimate of overall typical **long-term** volatility for the asset during the past 61 weeks (i.e., the testing period), while the second figure represents our estimate of **near-term** future volatility -- a prediction for the next 30 days.

Our approach provides two key advantages over simply relying on the Cboe VIX (S&P 500 Volatility Index) as a measure of asset volatility:

 - We provide a sector-based estimate, which as you will see from the data can differ significantly from overall S&P 500 volatility.

 - Our LSTM model with 'limited' input consistently achieves a higher out-of-sample R-squared score for volatility predictions compared to the VIX.

In [1]:
from pathlib import Path
import json

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import altair as alt

DATA_DIR = Path.cwd().parent / 'data'
NUM_TRIALS = 30

In [2]:
with open(DATA_DIR / 'volatility_results.json') as f:
    results = json.load(f)

In [3]:
etfs = list(results['1'].keys())
etfs

['BIL',
 'BND',
 'GLD',
 'HYG',
 'IEF',
 'IWM',
 'LQD',
 'QQQ',
 'SPY',
 'TIP',
 'TLT',
 'XLB',
 'XLE',
 'XLF',
 'XLI',
 'XLK',
 'XLP',
 'XLRE',
 'XLU',
 'XLV',
 'XLY']

In [4]:
# For each ETF, collect all sets of weekly predictions as a DataFrame
num_forecasts_per_trial = len(
    results['1'][etfs[0]]['LSTM']['limited']['test']['y_pred']
)
y_pred = {}
for etf in etfs:
    rows = []
    for i in range(NUM_TRIALS):
        # Add each trial as a row vector
        rows.append(
            results[str(i + 1)][etf]['LSTM']['limited']['test']['y_pred']
        )
    y_pred[etf] = pd.DataFrame(
        rows,
        columns=[f'Week_{i + 1}' for i in range(num_forecasts_per_trial)],
        index=pd.Series([str(i + 1) for i in range(NUM_TRIALS)], name='Trial')
    )

In [5]:
y_pred['SPY']

,Week_1,Week_2,Week_3,Week_4,Week_5,Week_6,Week_7,Week_8,Week_9,Week_10,...,Week_52,Week_53,Week_54,Week_55,Week_56,Week_57,Week_58,Week_59,Week_60,Week_61
Trial,,,,,,,,,,,,,,,,,,,,,
1,0.008724,0.009999,0.008617,0.010262,0.008527,0.008741,0.006798,0.007954,0.011197,0.009482,...,0.008874,0.008807,0.009422,0.010264,0.010816,0.010737,0.009148,0.008347,0.009173,0.008844
2,0.009543,0.011116,0.009215,0.009315,0.010147,0.008970,0.005752,0.008144,0.013302,0.011098,...,0.009887,0.009552,0.009800,0.011293,0.012099,0.011337,0.009606,0.008757,0.009759,0.009754
3,0.008852,0.010756,0.008483,0.009417,0.007761,0.008457,0.006786,0.009231,0.012347,0.008602,...,0.008578,0.007470,0.009323,0.010019,0.010387,0.010528,0.010159,0.008993,0.009023,0.009402
4,0.009581,0.010576,0.009631,0.011395,0.009312,0.009688,0.007859,0.008860,0.011682,0.010099,...,0.009473,0.009496,0.010081,0.010744,0.011009,0.010882,0.010217,0.009789,0.010153,0.009392
5,0.008973,0.010785,0.007728,0.009055,0.009150,0.008550,0.005813,0.007600,0.012482,0.010450,...,0.009122,0.008562,0.009528,0.010870,0.011532,0.010580,0.008882,0.008311,0.009367,0.009172
6,0.009399,0.010765,0.009740,0.010839,0.009232,0.009174,0.007550,0.008519,0.012197,0.010479,...,0.009803,0.009440,0.010101,0.010928,0.011414,0.011194,0.010025,0.009166,0.009799,0.009454
7,0.009710,0.011064,0.008384,0.009550,0.009974,0.009225,0.006295,0.008459,0.012240,0.010510,...,0.009308,0.009643,0.009850,0.011252,0.011780,0.010937,0.009307,0.008873,0.009972,0.009723
8,0.009684,0.011003,0.009494,0.010958,0.009731,0.009601,0.007352,0.008663,0.011913,0.010753,...,0.009967,0.009793,0.009961,0.011139,0.011658,0.011205,0.009910,0.009282,0.009959,0.009658
9,0.009463,0.010799,0.009484,0.011070,0.009635,0.009605,0.007226,0.008520,0.012034,0.010457,...,0.009597,0.009777,0.009975,0.010931,0.011424,0.011032,0.009972,0.009435,0.009848,0.009570
10,0.008997,0.010326,0.008534,0.010774,0.008688,0.008798,0.007193,0.007978,0.011311,0.009726,...,0.009187,0.009029,0.009960,0.010629,0.011138,0.011077,0.009516,0.009193,0.009457,0.008792
11,0.009339,0.010586,0.008669,0.009546,0.010070,0.009041,0.005838,0.007912,0.011842,0.010387,...,0.009144,0.009512,0.009531,0.010919,0.011467,0.010766,0.009351,0.008792,0.009742,0.009305
12,0.009535,0.011110,0.009585,0.010566,0.009747,0.009598,0.007161,0.008400,0.012185,0.010676,...,0.009905,0.009587,0.010212,0.011250,0.011853,0.011513,0.009941,0.009017,0.010076,0.009706
13,0.009855,0.010968,0.009601,0.011001,0.009811,0.010154,0.007647,0.008983,0.011985,0.010561,...,0.009699,0.009725,0.010227,0.011121,0.011376,0.010932,0.010041,0.009835,0.010354,0.009867
14,0.009603,0.011308,0.009310,0.010189,0.010023,0.009617,0.006382,0.008346,0.012749,0.010888,...,0.009893,0.009549,0.009892,0.011321,0.011987,0.011117,0.009745,0.008884,0.010068,0.009936
15,0.009542,0.010626,0.008709,0.010543,0.010078,0.009347,0.007024,0.008377,0.011895,0.010625,...,0.009658,0.009295,0.009918,0.010911,0.011312,0.010827,0.009430,0.009198,0.009928,0.009599
16,0.009553,0.010970,0.009295,0.011020,0.009345,0.009380,0.007235,0.008495,0.011942,0.010447,...,0.009587,0.009689,0.010116,0.011177,0.011657,0.011346,0.009814,0.009166,0.009893,0.009553
17,0.007004,0.008522,0.006831,0.007336,0.006758,0.006505,0.004281,0.006958,0.009943,0.007067,...,0.006531,0.006612,0.007659,0.008503,0.009437,0.009895,0.008607,0.006723,0.007594,0.007546
18,0.009521,0.010697,0.008772,0.011141,0.009341,0.009227,0.007547,0.008322,0.011580,0.010266,...,0.009574,0.009643,0.010472,0.011052,0.011369,0.011245,0.009945,0.009241,0.009983,0.009338
19,0.009563,0.010962,0.009147,0.010495,0.009850,0.009207,0.006851,0.008401,0.011759,0.010306,...,0.009363,0.009386,0.009700,0.011035,0.011576,0.010836,0.009521,0.008913,0.009880,0.009534
20,0.009420,0.011021,0.009170,0.009544,0.009827,0.008167,0.005917,0.008065,0.012579,0.010837,...,0.009612,0.009773,0.009638,0.011245,0.012062,0.011396,0.009700,0.008423,0.009668,0.009400
21,0.009695,0.010518,0.008684,0.010763,0.009894,0.009065,0.006912,0.008451,0.011773,0.010541,...,0.009350,0.009386,0.009792,0.010938,0.011250,0.010484,0.009227,0.009439,0.009940,0.009465
22,0.009273,0.011063,0.008935,0.010306,0.008976,0.009312,0.007284,0.008232,0.012020,0.009576,...,0.009146,0.009365,0.010421,0.010972,0.011662,0.011196,0.009842,0.009290,0.009824,0.009205
23,0.009214,0.010414,0.009370,0.011079,0.009165,0.009014,0.007606,0.008271,0.011667,0.010177,...,0.009636,0.009435,0.010249,0.010719,0.011211,0.011214,0.010065,0.009437,0.009727,0.009183
24,0.008225,0.010383,0.007953,0.009264,0.007177,0.007836,0.005839,0.008611,0.012358,0.008155,...,0.007728,0.006746,0.008335,0.009462,0.009949,0.010060,0.009849,0.009042,0.008259,0.008763
25,0.009329,0.010704,0.008595,0.010877,0.009737,0.009252,0.006686,0.008115,0.012099,0.010470,...,0.009517,0.009228,0.009923,0.010914,0.011459,0.010904,0.009561,0.009226,0.009865,0.009364
26,0.009591,0.011496,0.009876,0.010511,0.009854,0.009786,0.006698,0.008416,0.012736,0.011044,...,0.009974,0.009840,0.010138,0.011527,0.012358,0.011770,0.010109,0.009056,0.010021,0.009908
27,0.009599,0.011191,0.009659,0.010591,0.009862,0.009830,0.006927,0.008441,0.012375,0.010832,...,0.010005,0.009901,0.010048,0.011275,0.011977,0.011511,0.010111,0.009287,0.009922,0.009742
28,0.008622,0.010102,0.008091,0.010155,0.008353,0.008553,0.006821,0.007611,0.011051,0.009251,...,0.008873,0.008801,0.009727,0.010386,0.011006,0.011041,0.009301,0.008698,0.009117,0.008467
29,0.008539,0.009922,0.007966,0.009174,0.008212,0.008238,0.006145,0.007387,0.010745,0.008855,...,0.008221,0.008544,0.009346,0.010220,0.010743,0.010489,0.008835,0.008234,0.008998,0.008145
30,0.010026,0.011251,0.009067,0.010773,0.010462,0.010009,0.007374,0.009119,0.012114,0.010421,...,0.009601,0.009239,0.009932,0.011205,0.011592,0.011098,0.009757,0.009508,0.010341,0.009973

In [6]:
# Get the overall average volatility for each ETF during the test set period
print(f'Median annualized volatility prediction (over {
    NUM_TRIALS} trials on test set)\n---')
avg_annualized_vol = {}
for etf in etfs:
    avg_annualized_vol[etf] = y_pred[etf].mean().mean() * np.sqrt(252) * 100
avg_annualized_vol = pd.Series(
    avg_annualized_vol, name='Average Volatility (test set)'
)
avg_annualized_vol

Median annualized volatility prediction (over 30 trials on test set)
---

BIL      0.455343
BND      5.981263
GLD     17.093881
HYG      4.115452
IEF      6.526064
IWM     24.749133
LQD      7.831116
QQQ     22.536702
SPY     17.454022
TIP      5.498059
TLT     15.862322
XLB     20.572965
XLE     25.802990
XLF     22.216566
XLI     19.248253
XLK     25.005235
XLP     11.739381
XLRE    18.243003
XLU     16.848320
XLV     14.922235
XLY     24.739104
Name: Average Volatility (test set), dtype: float64

In [7]:
# Take an average of <30> trials of the latest predition on the test set
print(f'Most recent annualized volatility prediction (median for {
    NUM_TRIALS} trials)\n---')
recent_annualized_vol = {}
for etf in etfs:
    recent_annualized_vol[etf] = (
        np.median(y_pred[etf].values[:, -1]) * np.sqrt(252) * 100
    )
recent_annualized_vol = pd.Series(
    recent_annualized_vol, name='Recent Volatility (latest prediction)'
)
recent_annualized_vol

Most recent annualized volatility prediction (median for 30 trials)
---

BIL      0.401787
BND      4.718726
GLD     15.323170
HYG      2.878141
IEF      5.371611
IWM     23.034889
LQD      6.649408
QQQ     20.668170
SPY     14.966995
TIP      4.504144
TLT     14.339533
XLB     17.732679
XLE     27.833129
XLF     19.739298
XLI     18.014827
XLK     23.422370
XLP     11.419811
XLRE    16.231646
XLU     17.332471
XLV     14.888880
XLY     22.485580
Name: Recent Volatility (latest prediction), dtype: float64

In [8]:
df = pd.DataFrame([avg_annualized_vol, recent_annualized_vol]).T

In [9]:
df

      Average Volatility (test set)  Recent Volatility (latest prediction)
BIL                        0.455343                               0.401787
BND                        5.981263                               4.718726
GLD                       17.093881                              15.323170
HYG                        4.115452                               2.878141
IEF                        6.526064                               5.371611
IWM                       24.749133                              23.034889
LQD                        7.831116                               6.649408
QQQ                       22.536702                              20.668170
SPY                       17.454022                              14.966995
TIP                        5.498059                               4.504144
TLT                       15.862322                              14.339533
XLB                       20.572965                              17.732679
XLE                       25.802990                              27.833129
XLF                       22.216566                              19.739298
XLI                       19.248253                              18.014827
XLK                       25.005235                              23.422370
XLP                       11.739381                              11.419811
XLRE                      18.243003                              16.231646
XLU                       16.848320                              17.332471
XLV                       14.922235                              14.888880
XLY                       24.739104                              22.485580

In [10]:
df.to_csv(
    DATA_DIR / 'annualized_volatility_predictions.csv',
    index_label='ETF'
)